### ISSUE TITLE
option for first divider

### ISSUE THREAD

**Issue by passsy** [yqritc/RecyclerView-FlexibleDivider#15]
Please add an option to add a divider above the first item. Thanks!

**Comment by yqritc** [comment]
@passsy 
Sorry, I'm not planning to support header divider since supporting its feature lead to the complicated interface and code implementation.
I'll take it into consideration if more people request its feature, so please draw a line manually on top of the item/recyclerview for now, thanks.

**Comment by abhilash29** [comment]
Yes! Please add showFirstDivider

**Comment by ysmintor** [comment]
@abhilash29 you can make your own custom divider at current time!

**Comment by tanshion** [comment]
Yes! Please add showFirstDivider

**Comment by yintaibing** [comment]
Yes! Please add showFirstDivider

**Comment by wxmylife** [comment]
Yes! Please add showFirstDivider
