### ISSUE TITLE
Memory Growing Issue

### ISSUE THREAD

**Issue by AkoWu101** [yqritc/RecyclerView-FlexibleDivider#16]
just install sample project. Run on an emulator. Open Memory Monitor. Scroll up and down with several times. Memory is growing. Sometimes GC start, but cannot release more memory. Always call GC.

Any idea on this issue?

Thanks

**Comment by yqritc** [comment]
I checked by sample project. 
By scrolling up and down multiple times, memory usage grows and once GC starts, some memory gets released. Memory usage will be grown if no other application needs any memory. But once the memory usage is grown to the limit, memory is released and not increase any more.
I believe this is normal behaviour.
