### ISSUE TITLE
Show last divider works incorrectly, if the recycler view has more than one column

### ISSUE THREAD

**Issue by risayew** [yqritc/RecyclerView-FlexibleDivider#23]
The last divider is actually shown permanently, if the recycler view initialized with >1 columns (table-like).

**Comment by tobibo** [comment]
I created a pull request for this issue, not sure if that fits exactly into how the architecture of the project was designed. I assume this approach might get a bit bloated when support for other layout manager is needed.

**Comment by yqritc** [comment]
@tobibo 
Thanks for PR.
It is really nice one, but please let me think a bit since supporting GridLayoutManger does not fit the current functionality. I feel I should create new ItemDecoration class for GridLayoutManager.

**Comment by JulienDev** [comment]
:+1: for a support of GridLayoutManager, it's the only thing missing in your already great library ;)

**Comment by tobibo** [comment]
Yeah I do agree. Let me see if I  can come up with the separate ItemDecoration class implementation, shouldn't be too hard either.
