### ISSUE TITLE
Flashing divider when notifying multiple items changed

### ISSUE THREAD

**Issue by tom-pratt** [yqritc/RecyclerView-FlexibleDivider#26]
I'm using radio buttons in my cells in a horizontal linear layout.

I noticed that when calling notifyItemChanged on two cells at the same time, one to uncheck the radio button and one to check the radio button. That the dividers flash and glitch weirdly.

The above can be worked around by calling notifyDataSetChanged(). But the same problem occurs when calling notifyItemRemoved and notifyItemChanged at the same time which I haven't been able to work around whilst still getting the removed animation.

Thanks,
Tom

Example project
https://github.com/Sylapse/DividerSample.git

**Comment by yqritc** [comment]
@Sylapse 
Thanks for reporting this.
It seems old logic to handle recyclerview animator causes this problem.
I'll fix this and publish new version.

**Comment by yqritc** [comment]
@Sylapse 
I just published new version v1.2.8.
Please try it.

**Comment by tom-pratt** [comment]
@yqritc that has fixed it for me.

Thanks for the quick fix. Has helped me a lot with my current project!
