### ISSUE TITLE
No divider drawn using ItemAnimator 

### ISSUE THREAD

**Issue by JulienDev** [yqritc/RecyclerView-FlexibleDivider#29]
Hi,

I'm using an ItemAnimator with an Horizontal LinearLayoutManager. When I call notifyItemRemoved or notifyItemInserted the drawers are not drawn until I scroll to new items. It seems related to this issue https://code.google.com/p/android/issues/detail?id=100653 

Could it be possible to fix it?

Thanks !

**Comment by yqritc** [comment]
@JulienDev 
I believe this should not be happened.
I'll check this behaviour as soon as possible, thanks

**Comment by yqritc** [comment]
@JulienDev 
I checked, but could not see the problem.
Can u show ur sample project having this issue?

**Comment by jvbreen1** [comment]
@JulienDev I had a similar issue, and I fixed it by calling `invalidateItemDecorations()` on my `RecyclerView` when adding items. Hope this helps.

**Comment by JulienDev** [comment]
@jvbreen1 Thank you so much !
