### ISSUE TITLE
Include note about hardware acceleration

### ISSUE THREAD

**Issue by squeeish** [yqritc/RecyclerView-FlexibleDivider#3]
I had to do the following in Lollipop, Nexus 5 in order to get a dashed line to show up.
`recyclerView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);`

**Comment by yqritc** [comment]
Yes. I have written about this issue in my sample project.
https://github.com/yqritc/RecyclerView-FlexibleDivider/blob/master/sample/src/main/java/com/yqritc/recyclerviewflexibledivider/sample/ComplexActivity.java#L34

I also add note about it in ReadMe.
Thanks
