### ISSUE TITLE
draw divider on top of item instead of below

### ISSUE THREAD

**Issue by passsy** [yqritc/RecyclerView-FlexibleDivider#31]
From the [Material Design Spec](https://www.google.com/design/spec/components/dividers.html)

> Dividers are placed along the bottom edge of the content tiles, independent of the grid.

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B_udO5B8pzrzYi1pc290WFRMc1U/components_dividers_specs.png)

The current implementation draws the dividers below the item:

``` diff
        if (mDividerType == DividerType.DRAWABLE) {
-            bounds.top = child.getBottom() + params.topMargin + transitionY;
+            // I haven't tested the drawable implementation
+            bounds.top = child.getBottom() + params.topMargin + transitionY - dividerSize;
            bounds.bottom = bounds.top + dividerSize;
        } else {
-            bounds.top = child.getBottom() + params.topMargin + dividerSize / 2 + transitionY;
+            // this one works great
+            bounds.top = child.getBottom() + params.topMargin - dividerSize / 2 + transitionY;
            bounds.bottom = bounds.top;
        }
```

and this can be removed because the size does not change

``` diff
    @Override
    protected void setItemOffsets(Rect outRect, int position, RecyclerView parent) {
-        outRect.set(0, 0, 0, getDividerSize(position, parent));
+        outRect.set(0, 0, 0, 0);
    }
```

**This feature should be optional**

**Comment by yqritc** [comment]
@passsy 
Thanks for letting me know this!!

But the doc also states

> Dividers are 1dp thick, with an opacity of either 12% black in light themes or 12% white in dark themes.

So, I feel I should write gist or something instead of adding its feature to this library.

**Comment by passsy** [comment]
The correct styling of material dividers is easy. 

``` java
    .color(Color.parseColor("#1effffff")) // for dark themes
    .color(Color.parseColor("#1e000000")) // for light themes
    .sizeResId(R.dimen.dp1) // 1dp
```

The problem was the correct positioning of the divider which is not possible with the current API. I suggest a property like this for the `Builder` triggering the logic above:

``` java
    .positionInsideItem(true) // default false
```

**Comment by yqritc** [comment]
yes, u r right. I'll try to implement its feature in next version

**Comment by yqritc** [comment]
@passsy 
Added the feature at [v1.2.9](https://github.com/yqritc/RecyclerView-FlexibleDivider/releases/tag/1.2.9)

**Comment by passsy** [comment]
Works! Thank you
