### ISSUE TITLE
Divider at specific position

### ISSUE THREAD

**Issue by Vrutin** [yqritc/RecyclerView-FlexibleDivider#4]
How can I add the divider after a specific position.

I cannot seem to find it.

**Comment by yqritc** [comment]
Please see the following sample
https://github.com/yqritc/RecyclerView-FlexibleDivider/blob/master/sample/src/main/java/com/yqritc/recyclerviewflexibledivider/sample/ComplexAdapter.java#L108

You can control the visibility of divider by implementing FlexibleDividerDecoration.VisibilityProvider
