### ISSUE TITLE
shouldHideDivider not working

### ISSUE THREAD

**Issue by PSesto** [yqritc/RecyclerView-FlexibleDivider#40]
when set to true, divider is still showing

I can confirm that my adapter is implementing FlexibleDividerDecoration.VisibilityProvider and overriding shouldHideDivider.  I can also confirm that shouldHideDivider is not being called

**Comment by yqritc** [comment]
@PSesto 
Please check my sample project.
Complex Divider List (ComplexActivity) implements [VisibilityProvider](https://github.com/yqritc/RecyclerView-FlexibleDivider/blob/master/sample/src/main/java/com/yqritc/recyclerviewflexibledivider/sample/ComplexAdapter.java#L108).
I just checked the sample and it works well, so please check your implementation.

**Comment by PSesto** [comment]
You're right.  I didn't see the ".visibilityProvider(adapter)" line in ComplexActivity.  

Thank you so much for the quick response :)
