### ISSUE TITLE
why the divider color is not the same as that it should be?

### ISSUE THREAD

**Issue by jhwsx** [yqritc/RecyclerView-FlexibleDivider#59]
Hi, 
    I use the API as the doc says:

`recyclerView.addItemDecoration(
        new HorizontalDividerItemDecoration.Builder(this)
                .color(Color.RED)
                .sizeResId(R.dimen.divider)
                .marginResId(R.dimen.leftmargin, R.dimen.rightmargin)
                .build());`

However, I find that the color that shows is not the same as that it should be.
Could you please help me out?

**Comment by xushaun** [comment]
I have the same problem

**Comment by xushaun** [comment]
I find why i encounter this problem

**Comment by xushaun** [comment]
I find why i encounter this problem
I used colorResId(R.color.line_color) instead of color(R.color.line_color)  ,this solve the problem

**Comment by jhwsx** [comment]
I have had a try in my code according to you. It really works. If only I has known this half a month ago.
