### ISSUE TITLE
import fail?

### ISSUE THREAD

**Issue by baitouwei** [yqritc/RecyclerView-FlexibleDivider#8]
hi,i read the readme and import like this.

```
repositories {
    jcenter()
}

dependencies {
    compile 'com.yqritc:recyclerview-flexibledivider:1.2.3'
}
```

but it always fail like this.

```
Error:(40, 13) Failed to resolve: com.yqritc:recyclerview-flexibledivider:1.2.3
```

**Comment by yqritc** [comment]
@baitouwei 

mmm....
I re-tried the sample project and it does not return any errors.
Please compare your build.gradle file and sample one.
https://github.com/yqritc/RecyclerView-FlexibleDivider/blob/master/sample/build.gradle

If you can not find any difference, please clone repository and build sample project in your environment.
You may try to change the following line in dependencies to confirm lib file is located at jcenter.  
 Before

```
    compile project(':library')
```

After

```
    compile 'com.yqritc:recyclerview-flexibledivider:1.2.3'
```

Hope this helps.
