### ISSUE TITLE
support for headerDivider?

### ISSUE THREAD

**Issue by baitouwei** [yqritc/RecyclerView-FlexibleDivider#9]
It seem don't support for headerDivider but footerDivider.

**Comment by yqritc** [comment]
@baitouwei 
Sorry, I'm not planning to support header divider since supporting its feature lead to the complicated interface and code implementation.
I'll take it into consideration if more people request its feature.

**Comment by Rainer-Lang** [comment]
@yqritc Header and footer support shouldn't be very difficult: You "only" have to change the second divider (header divider) and the the before the last divider (footer divider).
For me +1 :)
